$('#next-description-2').click(function(){
  $('.feature-description-2').fadeIn('fast');
  $('.feature-description-1').hide();
});
$('#next-description-3').click(function(){
  $('.feature-description-3').fadeIn('fast');
  $('.feature-description-2').hide()
});
$('#next-description-1').click(function(){
  $('.feature-description-1').fadeIn('fast');
  $('.feature-description-3').hide()
});
